import { OfficeProject } from './types';

export const OFFICE_PROJECTS: OfficeProject[] = [
  {
    id: "the-edge-amsterdam",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Amsterdam",
    country: "Netherlands",
    typology: "contact",
    esgRating: "BREEAM Outstanding (98.4%)",
    area: "40,000 m²",
    year: "2015",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://www.plparchitecture.com",
    overview: "Regarded as one of the most sustainable and intelligent office buildings in the world, The Edge centers around a 15-story soaring glass atrium that acts as the thermal and social gravitational core of Deloitte's headquarters.",
    esgContext: "Achieved the highest BREEAM rating recorded (98.4%). Powered by 4,100 m² of rooftop solar arrays, aquifer thermal energy storage (ATES), rainwater flush systems, and Ethernet-powered LED smart sensory lighting.",
    designHighlights: [
      "Circadian daylight harvesting through a 15-story angled atrium",
      "Dynamic activity-based hot-desking with occupancy sensor feedback",
      "Vertical living gardens integrated into natural ventilation shafts",
      "Mesh acoustic baffle ceilings manufactured from recycled PET fibers"
    ],
    materials: ["Low-iron solar glazed facade", "FSC-certified European Oak", "Crushed aggregate terrazzo", "Recycled PET acoustic felt"]
  },
  {
    id: "bloomberg-european-hq",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "London",
    country: "United Kingdom",
    typology: "contact",
    esgRating: "BREEAM Outstanding (98.5%)",
    area: "102,190 m²",
    year: "2017",
    image: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://www.fosterandpartners.com",
    overview: "Occupying a full city block in central London, this benchmark commercial headquarters reimagines corporate workplace intimacy with a bronze stepped 'Vortex' atrium and custom integrated ceiling petals.",
    esgContext: "Awarded the RIBA Stirling Prize and a 98.5% BREEAM design score. Delivers a 73% water consumption saving and 35% reduction in energy usage via naturally ventilating bronze aerodynamic louvers.",
    designHighlights: [
      "Monumental timber-clad triple-helix spiral ramping through 6 stories",
      "Custom integrated ceiling panels with 500,000 embedded LED petals",
      "Dynamic acoustic dampening within double-height collaborative commons",
      "Rainwater catchment cooling towers supplying greywater fixtures"
    ],
    materials: ["English Derbyshire sandstone", "Japanese patinated bronze", "Micro-perforated acoustic timber", "Polished concrete screed"]
  },
  {
    id: "google-bay-view",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Mountain View, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED-NC v4 Platinum & ILFI LBC",
    area: "102,000 m²",
    year: "2022",
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://big.dk",
    overview: "Google's first ground-up campus featuring 'dragonscale' solar canopies that shade expansive, column-free interior floorplates organized as collaborative micro-neighborhoods on the upper deck.",
    esgContext: "Net water-positive campus with 100% renewable electricity 24/7. Geothermal pile heating and cooling system utilizes North America's largest ground-source heat pump installation.",
    designHighlights: [
      "Clerestory windows bring diffuse northern light into deep work plates",
      "Two-level interior layout separating high-activity social from focus desks",
      "Biophilic daylighting tuned to circadian rhythm transitions",
      "Acoustic felt ceiling baffles shaped into topographical contours"
    ],
    materials: ["Dragonscale photovoltaic glass", "Engineered mass timber", "Cradle-to-Cradle certified upholstery", "Recycled slag concrete"]
  },
  {
    id: "dyson-global-hq",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "HarbourFront",
    country: "Singapore",
    typology: "contact",
    esgRating: "BCA Green Mark Platinum",
    area: "13,000 m²",
    year: "2022",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://www.mmoser.com",
    overview: "An adaptive reuse of Singapore's historic 1927 coal-fired power station into Dyson's global technology headquarters, balancing preserved industrial red brick with cutting-edge acoustics and prototyping laboratories.",
    esgContext: "Certified BCA Green Mark Platinum. Preserved over 80% of original brick masonry, minimizing embodied carbon while outfitting the central turbine hall with smart HVAC air-induction jets.",
    designHighlights: [
      "Soaring four-story cathedral-like central turbine hall for town halls",
      "Cantilevered steel meeting pods suspended within heritage brick shells",
      "Precision acoustic control with micro-perforated blackened steel panels",
      "Internal spiraling black metal stair uniting R&D and executive hubs"
    ],
    materials: ["Restored colonial brick", "Blackened structural steel", "Solid American Walnut", "Acoustic fabric baffles"]
  },
  {
    id: "apple-park-interior",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Cupertino, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Platinum",
    area: "260,000 m²",
    year: "2017",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://www.apple.com",
    overview: "The interior architecture of 'The Ring' is constructed around modular bespoke timber work pods ('pods') that repeat along the mile-long circumference, framing uninterrupted views of 9,000 drought-tolerant native trees.",
    esgContext: "100% renewable energy generated by a 17-megawatt rooftop solar installation and biogas fuel cells. Natural ventilation operates 9 months of the year without mechanical chillers.",
    designHighlights: [
      "Custom 18-foot solid white oak collaboration tables by Arco",
      "Seamless terrazzo floors polished with custom aggregate matrices",
      "Acoustic perforations laser-drilled into polished maple ceiling planks",
      "Frameless curved low-iron glass facades maximizing visual biophilia"
    ],
    materials: ["Custom white oak", "Monolithic cast terrazzo", "Low-iron curved glass", "Brushed cast aluminum"]
  },
  {
    id: "airbnb-888-brannan",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "San Francisco, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Gold Certified",
    area: "16,000 m²",
    year: "2014",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://www.wrnsstudio.com",
    overview: "A converted 1917 century-old industrial battery factory featuring a central daylight-flooded four-story atrium flanked by exact full-scale architectural replicas of beloved international Airbnb listings.",
    esgContext: "Preserved mass-timber structural posts and historic brick facade, diverting 90% of demolition waste. Natural light penetrates through restored industrial sawtooth skylights.",
    designHighlights: [
      "Meeting rooms meticulously modeled after global listings in Milan, Bali, and Kyoto",
      "Custom three-story living wall containing over 1,200 native fern varieties",
      "Agile open-plan lounges without assigned seating for nomadic collaboration",
      "Internal timber boardwalks facilitating serendipitous informal encounters"
    ],
    materials: ["Century-old heavy timber", "Industrial corrugated mesh", "Living green wall", "Polished warehouse concrete"]
  },
  {
    id: "lego-campus",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Billund",
    country: "Denmark",
    typology: "contact",
    esgRating: "LEED Gold Certified",
    area: "54,000 m²",
    year: "2022",
    image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://www.cfmoller.com",
    overview: "Designed around the philosophy of 'learning and working through play', the campus brings together eight building modules under sweeping daylighting with oversized yellow staircase pavilions and circular focus corners.",
    esgContext: "Engineered with energy-efficient geothermal heat loops, rooftop sedum green roofs, and circular interior materials including acoustic panels pressed from shredded waste Lego bricks.",
    designHighlights: [
      "Central circular timber community lounge nicknamed 'The People House'",
      "Acoustic paneling manufactured directly from recycled toy plastics",
      "Dynamic color blocking supporting spatial wayfinding and creative moods",
      "Outdoor roof garden circuits for walking meetings and relaxation"
    ],
    materials: ["Recycled ABS plastic acoustic panels", "Nordic spruce cladding", "Linoleum flooring", "Terrazzo tiles"]
  },
  {
    id: "salesforce-ohana-floor",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "San Francisco, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Platinum",
    area: "1,850 m²",
    year: "2018",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://www.cavagnero.com",
    overview: "Perched on the 61st floor of Salesforce Tower, the top penthouse floor was intentionally dedicated not to executive offices, but as a double-height community 'Ohana' garden lounge with 360-degree Pacific panoramic views.",
    esgContext: "Part of the tallest LEED Platinum commercial building in the Western US, equipped with blackwater recycling systems, 100% natural daylighting, and zero-VOC non-toxic furnishings throughout.",
    designHighlights: [
      "Over 24-foot tall living perimeter columns clad in lush tropical epiphytes",
      "Curved barista bars fabricated from solid figured claro walnut slabs",
      "Grand acoustic timber slat ceilings concealing state-of-the-art AV arrays",
      "Flexible auditorium furniture allowing instant conversion to civic benefits"
    ],
    materials: ["Claro Walnut slabs", "Italian Travertine stone", "Acoustic micro-slat ceilings", "Hand-knotted wool rugs"]
  },
  {
    id: "slack-hq-sf",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "San Francisco, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Silver Certified",
    area: "21,300 m²",
    year: "2018",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://o-plus-a.com",
    overview: "Spanning 10 storeys, Slack's headquarters is conceptualized as an urban expedition along the Pacific Crest Trail, with each floor transitioning through distinct wilderness ecosystems from deserts to alpine forests.",
    esgContext: "Low-VOC paint finishes, water-saving sub-metering, circadian task lighting fixtures, and maximum integration of reclaimed Pacific Northwest red cedar logs.",
    designHighlights: [
      "Lobby tent pavilions with translucent back-illuminated acoustic textile sails",
      "Deep focus libraries designed as alpine ice-cave acoustic sanctuaries",
      "Central canyon stair with raw timber treads encouraging cardiovascular movement",
      "Collaborative booths lined with textured acoustic mosses and wool felt"
    ],
    materials: ["Western Red Cedar", "Textured acoustic felt", "Black steel rebar", "Preserved reindeer moss"]
  },
  {
    id: "red-bull-amsterdam",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Amsterdam",
    country: "Netherlands",
    typology: "contact",
    esgRating: "Circular Renovation Certified",
    area: "3,200 m²",
    year: "2016",
    image: "https://images.unsplash.com/photo-1531973576160-7125cd663d86?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://studioninedots.nl",
    overview: "Set inside a former shipbuilding warehouse in Amsterdam's creative NDSM wharf, the design juxtaposes dark triangular steel facets with the brutalist concrete bones of the industrial dockyard.",
    esgContext: "Preserved 100% of existing historical crane gantries and steel trusses, relying on passive natural ventilation across harbor winds and radiant floor heating.",
    designHighlights: [
      "Deconstructed faceted black metal pods slicing through open volumes",
      "Skateboarding ramps seamlessly blended into meeting transitions",
      "Acoustic quiet rooms lined with dark perforated recycled felt",
      "DJ booths and creative labs overlooking the IJ waterfront"
    ],
    materials: ["Raw steel plate", "Industrial crane concrete", "Perforated rubber flooring", "Exposed electrical conduits"]
  },
  {
    id: "beats-by-dre-hq",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Culver City, CA",
    country: "United States",
    typology: "contact",
    esgRating: "AIA Award Winner",
    area: "9,800 m²",
    year: "2014",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://bestorarchitecture.com",
    overview: "A sprawling campus designed specifically for acoustic engineering and creative rhythm, featuring bold saturation, custom wooden barn pavilions, and open collaboration plazas.",
    esgContext: "Comprehensive energy retrofit of two industrial warehouses, featuring operable skylight arrays, radiant polished slab heating, and zero-VOC water-based sealants.",
    designHighlights: [
      "Custom deep-blue architectural wood pavilions creating nested neighborhoods",
      "Precision sound-isolated listening booths calibrated for audiophile testing",
      "White oak courtyards linking engineering labs to video production studios",
      "Sky-lit collaboration cafes with banquette booths finished in brass detailing"
    ],
    materials: ["Stained Baltic birch plywood", "Acoustic bass traps", "Hand-rubbed brass accents", "Sealed industrial concrete"]
  },
  {
    id: "nike-serena-williams",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Beaverton, OR",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Platinum",
    area: "93,000 m²",
    year: "2022",
    image: "https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://skylabarchitecture.com",
    overview: "The largest structure on Nike's global campus, containing world-class design studios, materials research labs, and an indoor Olympic-regulation track looping through creative open-floor office suites.",
    esgContext: "LEED Platinum certified. Over 20% of construction materials sourced within a 500-mile radius, coupled with a 1,200-panel rooftop photovoltaic installation and biophilic wetland catchment.",
    designHighlights: [
      "Acoustic felt ceiling topography tuned to reduce footwear testing reverberation",
      "Material exploration corridors lined with glass-encased raw textile archives",
      "Cantilevered design suites overlooking preserved Pacific Northwest wetlands",
      "Modular work benches wired for high-speed rapid 3D prototyping"
    ],
    materials: ["Regional Douglas Fir", "Local volcanic basalt stone", "Recycled foam underlay", "Triple-glazed thermal curtain"]
  },
  {
    id: "unilever-four-acres",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "London",
    country: "United Kingdom",
    typology: "contact",
    esgRating: "WELL Gold & BREEAM Excellent",
    area: "14,500 m²",
    year: "2020",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://perkinswill.com",
    overview: "A transformative executive development and agile workspace campus emphasizing holistic employee wellness, circadian natural daylighting, and zero-distraction focus enclaves.",
    esgContext: "WELL Building Standard Gold verified. Advanced particulate air-filtration systems supply 30% more fresh oxygen than standard codes require, paired with 100% renewable grid power.",
    designHighlights: [
      "Circadian biodynamic lighting automatically shifting blue/warm Kelvin tones",
      "Living moss baffles improving indoor air hygiene and ambient speech privacy",
      "Stepped timber amphitheaters equipped for global live-broadcast town halls",
      "Ergonomic height-adjustable benching featuring sustainable bamboo desktop slabs"
    ],
    materials: ["Carbonized bamboo", "Preserved Norwegian reindeer moss", "Wool acoustic wall fabrics", "Zero-VOC milk paints"]
  },
  {
    id: "uber-mission-bay",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "San Francisco, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Gold Certified",
    area: "42,000 m²",
    year: "2021",
    image: "https://images.unsplash.com/photo-1568992687947-868a62a9f521?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://www.shoparc.com",
    overview: "Consisting of two connected mid-rise towers, this headquarters introduces the 'Commons'—a multi-story cascading glazed circulation path with operable glass facades that bring open-air breezes directly into work lounges.",
    esgContext: "Automated computer-controlled facade louvers eliminate traditional air conditioning demands for up to 6 months of the year, reducing HVAC energy demands by 38%.",
    designHighlights: [
      "Operable glass panels transforming interior corridors into open-air verandas",
      "Warm timber bridges linking collaborative hubs across soaring interior atriums",
      "Bespoke sound-masking pink noise emitters calibrated throughout focus decks",
      "Integrated micro-kitchens fostering spontaneous team collisions"
    ],
    materials: ["Anodized bronze aluminum", "White Ash wall battens", "High-performance low-E glass", "Cast architectural concrete"]
  },
  {
    id: "meta-mpk-21",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Menlo Park, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Platinum v4",
    area: "48,000 m²",
    year: "2018",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://www.foga.com",
    overview: "Conceived by Frank Gehry, MPK 21 is crowned by a 3.6-acre rooftop park with 200 trees. The single-room interior workplace beneath is an expansive, democratic landscape free of private executive offices.",
    esgContext: "LEED Platinum v4 certified. Saves 17 million gallons of water annually through an on-site recycled water treatment system, supported by a 1.4 MW photovoltaic roof canopy.",
    designHighlights: [
      "Continuous undulating roofline bouncing diffuse daylight across deep workstations",
      "3.6-acre rooftop park with half-mile walking loops accessible from open floorplates",
      "Collaborative street called 'The Town Square' hosting maker spaces and cafes",
      "Commissioned installations from contemporary Californian artists throughout"
    ],
    materials: ["Exposed structural steel trusses", "Reclaimed western redwood", "Acoustic spray cellulose", "Polished slab flooring"]
  },
  {
    id: "deloitte-the-butterfly",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Tokyo",
    country: "Japan",
    typology: "contact",
    esgRating: "CASBEE S-Rank & WELL Gold",
    area: "18,000 m²",
    year: "2021",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://kkaa.co.jp",
    overview: "Crafted by Kengo Kuma, this headquarters applies traditional Japanese 'Kigumi' timber joinery into a forward-looking agile workplace, balancing tatami-inspired focus pods with panoramic Tokyo skyline views.",
    esgContext: "Certified CASBEE S-Rank. Sourced 100% of cedar louvers from sustainably managed Japanese prefectural forests, significantly sequestering embodied carbon.",
    designHighlights: [
      "Intricate interlocking Hinoki cedar screens dividing conference areas",
      "Washi paper acoustic light fixtures softening ambient glare",
      "Zoned activity-based workplace allowing seamless transition between team and solo modes",
      "Zen moss interior courtyards offering tactile stress relief"
    ],
    materials: ["Japanese Hinoki Cedar", "Handmade Washi paper", "Brushed granite stone", "Textured tatami mats"]
  },
  {
    id: "bbc-mediacityuk",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Salford",
    country: "United Kingdom",
    typology: "contact",
    esgRating: "BREEAM Excellent",
    area: "31,500 m²",
    year: "2011",
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://www.sheppardrobson.com",
    overview: "A pioneer of Activity-Based Working (ABW), the BBC Salford hub removed dedicated desks for 2,500 staff in favor of ergonomic work booths, broadcast production pods, and digital collaboration rings.",
    esgContext: "Reduced real estate footprint by 30% through advanced desk-sharing metrics, saving over 4,000 metric tons of operational CO2 annually.",
    designHighlights: [
      "Iconic rainbow-upholstered circular conversation pods with acoustic linings",
      "Open broadcast studios integrated directly into employee circulation paths",
      "Flexible newsroom floorplates easily reconfigurable during breaking events",
      "High-absorption ceiling baffles controlling microphone bleed"
    ],
    materials: ["Molded plywood shells", "Heavy-duty Camira wool upholstery", "Powder-coated steel frames", "Sound-dampening vinyl flooring"]
  },
  {
    id: "fiverr-hq",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Tel Aviv",
    country: "Israel",
    typology: "contact",
    esgRating: "Green Star Renovation",
    area: "4,500 m²",
    year: "2018",
    image: "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://setter.co.il",
    overview: "Located within an eight-story 1960s heritage structure in southern Tel Aviv, this interior celebrates local craftsmanship with exposed aged concrete, salvaged Jerusalem brick, and bespoke artisan steelwork.",
    esgContext: "Retained original load-bearing concrete pillars and perimeter windows, eliminating extensive embodied carbon while integrating energy-efficient VRF climate control.",
    designHighlights: [
      "Custom steel-and-glass partitions admitting natural light deep into central zones",
      "Casual library nooks lined with locally reclaimed Ottoman terracotta tiles",
      "Bespoke plant hanging systems suspended from industrial concrete beams",
      "Rooftop wooden deck overlooking the Mediterranean coastline"
    ],
    materials: ["Aged concrete pillars", "Reclaimed Jerusalem brick", "Raw oiled steel", "Terracotta tile pavers"]
  },
  {
    id: "linkedin-emea-dublin",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Dublin",
    country: "Ireland",
    typology: "contact",
    esgRating: "LEED Platinum & WELL Certified",
    area: "17,650 m²",
    year: "2017",
    image: "https://images.unsplash.com/photo-1497366412874-3415097a27e7?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://interiorarchitects.com",
    overview: "LinkedIn's international headquarters celebrates Irish heritage through distinct themed wings, unified by a central social atrium with double-height video boards and barista bars.",
    esgContext: "LEED Platinum and WELL certified. Incorporates rainwater harvesting, district cooling connections, 100% non-toxic finishes, and extensive end-of-trip cyclist facilities.",
    designHighlights: [
      "Spacious double-height community amphitheater hosting international symposiums",
      "Irish folklore themed collaboration rooms lined with custom acoustic felt murals",
      "Dedicated wellness floor featuring meditation spaces and yoga studios",
      "Modular breakout booths equipped with wireless presentation screens"
    ],
    materials: ["Irish bog oak accents", "Recycled wool felt", "Acoustic micro-slat timber", "Terrazzo counter surfaces"]
  },
  {
    id: "pinterest-hq-sf",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "San Francisco, CA",
    country: "United States",
    typology: "contact",
    esgRating: "AIA San Francisco Honor Award",
    area: "9,300 m²",
    year: "2016",
    image: "https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://iwamotoscott.com",
    overview: "A transformed agricultural warehouse in the SOMA district, anchored by an origami-folded central wood-and-steel stair that pierces through a massive light-filled central atrium.",
    esgContext: "High-efficiency automated louvers, localized dimming controls, recycled timber framing, and direct integration with San Francisco's urban transit corridor.",
    designHighlights: [
      "Complex geometric wood pavilion known as 'The Knitted Stair'",
      "Maker labs stocked with silkscreen, letterpress, and craft tools for employees",
      "Perforated plywood acoustic ceilings controlling ambient chatter",
      "Corner phone booths lined with customized patterned soundproofing tiles"
    ],
    materials: ["Milled Baltic birch plywood", "Perforated blackened steel", "Sealed exposed timber joists", "Industrial felt baffles"]
  },
  {
    id: "zurich-insurance-hq",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Zurich",
    country: "Switzerland",
    typology: "contact",
    esgRating: "2000-Watt Society & Minergie-P",
    area: "24,000 m²",
    year: "2020",
    image: "https://images.unsplash.com/photo-1504384764586-bb4cdc1707b0?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://krischanitz.at",
    overview: "Resting beside Lake Zurich, this corporate headquarters unites historic turn-of-the-century heritage halls with a state-of-the-art timber-lined atrium flooded with crystalline alpine daylight.",
    esgContext: "Certified Swiss Minergie-P and compliant with 2000-Watt Society sustainability criteria. Powered by heat exchange pumps utilizing deep glacial lake water from Lake Zurich.",
    designHighlights: [
      "Monumental timber atrium stair fostering spontaneous inter-departmental dialogue",
      "Custom acoustic timber slats tuned for quiet, focused administrative work",
      "Panoramic executive boardrooms overlooking the Swiss Alps and lake",
      "Ergonomic Swiss Vitra task chairs customized for neutral posture support"
    ],
    materials: ["Swiss Silver Fir", "Lake Zurich limestone", "Acoustic micro-perforated timber", "Low-reflection museum glass"]
  },
  {
    id: "adobe-100-hooper",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "San Francisco, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Platinum Certified",
    area: "26,000 m²",
    year: "2019",
    image: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://vdt.com",
    overview: "Located in San Francisco's historic PDR (Production, Distribution, and Repair) zone, this Adobe facility celebrates design makers with interactive digital art galleries, open-source workshops, and cantilevered communal terraces.",
    esgContext: "LEED Platinum certified. Features dynamic glass that automatically tints according to sun angles, minimizing glare and cooling load by 28%.",
    designHighlights: [
      "Custom-designed interactive light installation responding to employee foot traffic",
      "Raw blackened steel bridges spanning light wells between team suites",
      "Quiet focus libraries upholstered in sound-absorbing midnight wool",
      "Maker labs equipped with laser cutters, 3D printers, and textile looms"
    ],
    materials: ["SageGlass electrochromic glazing", "Blackened steel bar joists", "Reclaimed factory pine", "Recycled wool upholstery"]
  },
  {
    id: "sony-music-hq-london",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "London",
    country: "United Kingdom",
    typology: "contact",
    esgRating: "BREEAM Excellent",
    area: "9,000 m²",
    year: "2018",
    image: "https://images.unsplash.com/photo-1497215641119-bbe6d71eeeae?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://universaldesignstudio.com",
    overview: "A sophisticated headquarters celebrating sound and performance, centered around a monumental double-height patinated brass and acoustic timber atrium designed for live artist showcases.",
    esgContext: "BREEAM Excellent certified, utilizing smart building sensors, recycled brass cladding, and localized air handling systems for high-occupancy performance zones.",
    designHighlights: [
      "Hand-patinated bronze staircase serving as a podium for impromptu gigs",
      "Private recording and listening lounges lined with sound-insulating acoustic wool",
      "Custom stained walnut bar serving as a casual meeting and celebration core",
      "Bespoke lighting fixtures casting warm theatrical illumination"
    ],
    materials: ["Hand-patinated architectural brass", "Stained European walnut", "Textured acoustic felt", "Terrazzo flooring"]
  },
  {
    id: "medibank-place",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Melbourne",
    country: "Australia",
    typology: "contact",
    esgRating: "6 Star Green Star & WELL Platinum",
    area: "30,500 m²",
    year: "2014",
    image: "https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://hassellstudio.com",
    overview: "Australia's landmark 'Health-Based Working' (HBW) facility, designed around the thesis that active movement improves human vitality, featuring a dramatic looping ramp and 2,300 interior plants.",
    esgContext: "Achieved 6 Star Green Star Design. Natural daylight reaches 80% of desks, while over 520 linear meters of lush green plant facades scrub indoor air toxins.",
    designHighlights: [
      "Iconic spiraling cobalt blue and timber ramp connecting all collaborative decks",
      "Indoor multipurpose athletic courts and yoga studios directly off main hallways",
      "26 distinct workplace typologies ranging from acoustic quiet pods to bustling plazas",
      "Over 2,300 living indoor plants integrated into furniture and walls"
    ],
    materials: ["Australian Spotted Gum timber", "Recycled rubber athletic flooring", "Lush living foliage", "Curved molded glass"]
  },
  {
    id: "stripe-urban-hq",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Dublin",
    country: "Ireland",
    typology: "contact",
    esgRating: "LEED Gold Certified",
    area: "14,000 m²",
    year: "2020",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://stwarchitects.com",
    overview: "Built overlooking Dublin's Silicon Docks, this workplace embraces crisp Scandinavian minimalism, balancing deep acoustic concentration pods with radiant communal cafeterias.",
    esgContext: "Certified LEED Gold. Advanced daylight sensors adjust LED output dynamically, while solar thermal arrays preheat water for all building operations.",
    designHighlights: [
      "Floor-to-ceiling glass pavilions framing maritime views of the River Liffey",
      "Acoustically isolated glass telephone booths wrapped in natural felt",
      "Central barista lounge designed as an informal coffee and tech discussion node",
      "Ergonomic Scandinavian sit-stand workstations paired with biophilic dividers"
    ],
    materials: ["Bleached white oak", "Brushed stainless steel", "Acoustic Kvadrat textiles", "Low-iron acoustic glazing"]
  },
  {
    id: "spotify-hq-stockholm",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Stockholm",
    country: "Sweden",
    typology: "contact",
    esgRating: "BREEAM Very Good",
    area: "19,000 m²",
    year: "2018",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://tpbennett.com",
    overview: "Spread across 17 floors in the heart of Stockholm, Spotify's flagship workplace reflects music culture with recording studios, neon-lit listening lounges, and agile squad rooms.",
    esgContext: "100% powered by Swedish hydroelectric and wind energy, featuring locally manufactured Swedish furniture that minimizes logistics emissions.",
    designHighlights: [
      "Custom acoustic squad rooms calibrated with sound-absorbing baffles",
      "Dynamic gaming and jam lounges equipped with professional instruments",
      "Vibrant color coding delineating team zones and circulation arteries",
      "Panoramic rooftop terrace with 360-degree views across Gamla Stan"
    ],
    materials: ["Swedish Pine", "Perforated acoustic panels", "Vibrant neon accents", "Epoxy terrazzo floors"]
  },
  {
    id: "asos-greater-london-house",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "London",
    country: "United Kingdom",
    typology: "contact",
    esgRating: "BREEAM Good Certified",
    area: "23,000 m²",
    year: "2018",
    image: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://spacelab.co.uk",
    overview: "A transformative renovation of Camden's famous 1920s Art Deco Carreras Cigarette Factory into a cutting-edge fashion and e-commerce creative headquarters.",
    esgContext: "Retained the vast heritage structural grid, preventing thousands of tons of embodied carbon release while installing energy-saving secondary double glazing.",
    designHighlights: [
      "Dramatic central staircase cascading through three open-plan studio levels",
      "Professional photographic catwalks and photography studios built into work floors",
      "Expansive communal cafes modeled after contemporary hotel lobbies",
      "Art Deco inspired brass light pendants and fluted glass partitions"
    ],
    materials: ["Fluted glass", "Polished brass trim", "Heritage concrete columns", "Herringbone timber parquet"]
  },
  {
    id: "wework-110-wall-st",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "New York, NY",
    country: "United States",
    typology: "contact",
    esgRating: "Energy Star Certified",
    area: "12,000 m²",
    year: "2016",
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://wework.com",
    overview: "A quintessential Manhattan adaptive co-working environment featuring exposed structural brick, custom blackened steel mullions, and lively community pantries.",
    esgContext: "Full interior upgrade of a 1960s financial tower, implementing high-efficiency variable-speed fans and localized occupancy-based LED dimming circuits.",
    designHighlights: [
      "Signature industrial black-mullion glass offices balancing transparency and privacy",
      "Cozy residential-style leather seating nooks with curated vintage art walls",
      "Central micro-brewery pantries encouraging informal member networking",
      "Acoustically treated phone nooks with bespoke graphic wallpapers"
    ],
    materials: ["Reclaimed Manhattan brick", "Blackened steel mullions", "Distressed saddle leather", "Solid white oak flooring"]
  },
  {
    id: "canva-global-hq",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Surry Hills, Sydney",
    country: "Australia",
    typology: "contact",
    esgRating: "Green Star 5-Star Equivalent",
    area: "8,500 m²",
    year: "2021",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://valmont.com.au",
    overview: "Located in Sydney's creative Surry Hills district, Canva's flagship space champions community dining, plant-rich spaces, and flexible design studios for thousands of designers.",
    esgContext: "Zero single-use plastics campus with on-site commercial composting, an organic rooftop herb garden, and 100% green electricity contracts.",
    designHighlights: [
      "Large commercial demonstration kitchen where chefs prepare daily communal team lunches",
      "Biophilic rooftop farm growing herbs and vegetables for employee meals",
      "Playful bespoke presentation amphitheaters with integrated power plugs",
      "Acoustic felt ceiling baffles shaped like floating design canvases"
    ],
    materials: ["Australian Blackbutt timber", "Terrazzo dining benches", "Acoustic ceiling felt", "Recycled brick pavers"]
  },
  {
    id: "dropbox-hq-sf",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "San Francisco, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Gold Certified",
    area: "28,000 m²",
    year: "2016",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://avroko.com",
    overview: "Departing from stereotypical tech tropes, Dropbox HQ draws inspiration from boutique hotels, featuring 'The Tuck Shop' cafeteria, walnut-paneled speakeasies, and deep focus libraries.",
    esgContext: "Certified LEED Gold. Advanced sub-metering, low-VOC finishes, daylight-responsive dimming, and extensive bike storage encouraging low-carbon commuting.",
    designHighlights: [
      "The Library: A silent sanctuary wrapped in blackened walnut and warm reading lamps",
      "The Tuck Shop: A world-renowned hospitality cafeteria with custom industrial lighting",
      "The Porch: A casual collaborative lounge with residential furniture groupings",
      "Acoustic fabric wrapped walls throughout all conference spaces"
    ],
    materials: ["Blackened walnut", "Antiqued brass hardware", "Handmade ceramic tile", "Plush velvet upholstery"]
  },
  {
    id: "microsoft-silicon-valley",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Mountain View, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Platinum & Net-Zero Water",
    area: "59,700 m²",
    year: "2021",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://wrnsstudio.com",
    overview: "The largest mass timber commercial building in North America at completion, featuring cross-laminated timber (CLT) interior ceilings, living courtyards, and net-zero water recycling.",
    esgContext: "First tech campus with Net-Zero Water certification under the Living Building Challenge. 100% of non-potable water is treated on-site via an engineered wetland.",
    designHighlights: [
      "Exposed Cross-Laminated Timber (CLT) beams bringing tactile biophilic warmth",
      "Courtyards connecting indoor workspaces directly to restored native oak woodlands",
      "Integrated micro-climates that allow employees to choose their preferred thermal zone",
      "Advanced acoustic spray finishes preserving speech privacy in open volumes"
    ],
    materials: ["Cross-Laminated Timber (CLT)", "Sustainably harvested Douglas fir", "Permeable paver stone", "Recycled steel connections"]
  },
  {
    id: "warner-music-arts-district",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Los Angeles, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Gold Certified",
    area: "24,000 m²",
    year: "2019",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://rockwellgroup.com",
    overview: "A dramatic transformation of a 1912 former Ford Model T assembly plant in downtown LA's Arts District, blending gritty industrial heritage with tailored music recording studios and performance spaces.",
    esgContext: "Saved over 12,000 tons of carbon emissions by salvaging the concrete mushroom columns and brick walls, pairing them with modern high-efficiency VRV climate control.",
    designHighlights: [
      "Restored industrial concrete mushroom columns anchoring open creative suites",
      "Double-height recording studios with floating acoustic isolation floors",
      "A 250-person performance hall hosting intimate record label showcases",
      "Rooftop swimming pool and lounge with vistas of the Los Angeles skyline"
    ],
    materials: ["Historic concrete columns", "Exposed bowstring wood trusses", "Blackened steel mullions", "Custom velvet drapery"]
  },
  {
    id: "booking-com-city-campus",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Amsterdam",
    country: "Netherlands",
    typology: "contact",
    esgRating: "BREEAM Excellent",
    area: "65,000 m²",
    year: "2023",
    image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://unstudio.com",
    overview: "Conceived as an urban 'vertical village', this massive waterfront building connects diverse cultures with themed interior micro-communities, sweeping staircases, and lush green courtyards.",
    esgContext: "Achieved BREEAM Excellent. Connected to an aquifer thermal energy storage (ATES) system, outfitted with solar glass and smart LED daylight regulation.",
    designHighlights: [
      "Sweeping sculpted green staircases uniting multi-story open atriums",
      "Dynamic themed breakout lounges reflecting global travel destinations",
      "Abundant natural daylight reaching deep inside through central light shafts",
      "Acoustic felt pods providing high-focus individual work pods"
    ],
    materials: ["Curved stainless steel balustrades", "European Ash timber", "Terrazzo floor slabs", "Acoustic recycled felt"]
  },
  {
    id: "github-hq-sf",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "San Francisco, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Certified",
    area: "5,100 m²",
    year: "2013",
    image: "https://images.unsplash.com/photo-1531973576160-7125cd663d86?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://github.com",
    overview: "Famous for its playful Oval Office replica lobby, vintage speakeasy bars, and coding pods, GitHub's headquarters is designed as a comfortable social home for open-source developers.",
    esgContext: "Restored a historic 3-story brick warehouse, retaining original Douglas fir timber posts, exposed brickwork, and natural daylighting from perimeter windows.",
    designHighlights: [
      "The Oval Office: An exact replica presidential suite serving as the reception hub",
      "Secret speakeasy bar concealed behind a library bookcase for evening socials",
      "Cozy coding pods with warm directional task lighting and plush banquettes",
      "In-house coffee bar with trained baristas for morning community connections"
    ],
    materials: ["Reclaimed California Redwood", "Exposed red clay brick", "Industrial pipe steel", "Chesterfield leather"]
  },
  {
    id: "hyundai-capital-convention",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Seoul",
    country: "South Korea",
    typology: "contact",
    esgRating: "LEED Gold Certified",
    area: "21,000 m²",
    year: "2019",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://gensler.com",
    overview: "A sleek, geometric financial headquarters featuring a monolithic white acoustic amphitheater, integrated multimedia surfaces, and minimalist focus suites.",
    esgContext: "Certified LEED Gold. Employs smart building management systems that dynamically dim lighting and optimize air flow depending on real-time desk occupancy.",
    designHighlights: [
      "Monolithic white amphitheater serving as a town hall and media production zone",
      "Precision laser-cut acoustic panels minimizing echo in large gathering areas",
      "Executive meeting rooms featuring concealed digital presentation displays",
      "Linear LED lighting embedded seamlessly into polished architectural concrete"
    ],
    materials: ["White solid surface Corian", "Anodized aluminum panels", "Acoustic micro-perforated wood", "Monolithic poured resin"]
  },
  {
    id: "etsy-brooklyn-hq",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Brooklyn, NY",
    country: "United States",
    typology: "contact",
    esgRating: "Living Building Challenge Petal & LEED Platinum",
    area: "18,500 m²",
    year: "2016",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://gensler.com",
    overview: "One of the greenest buildings in New York City, Etsy's Brooklyn office is a living laboratory of non-toxic, locally crafted materials, with hundreds of works made by Etsy sellers.",
    esgContext: "Living Building Challenge Petal Certified and LEED Platinum. All wood is FSC-certified or reclaimed. Free of all 'Red List' toxic chemicals throughout all furniture and adhesives.",
    designHighlights: [
      "Over 750 works of art and furniture commissioned directly from local Etsy artisans",
      "Rainwater cistern collection providing irrigation for extensive indoor living walls",
      "Quiet library and craft labs equipped with sewing and knitting machines for staff",
      "Solar rooftop arrays supplying clean electricity to the building grid"
    ],
    materials: ["FSC-certified salvaged water tower cedar", "Non-toxic milk paint", "Handmade ceramic tiles", "Living plant foliage"]
  },
  {
    id: "king-games-stockholm",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Stockholm",
    country: "Sweden",
    typology: "contact",
    esgRating: "Nordic Green Building Standard",
    area: "6,500 m²",
    year: "2015",
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://adolfssonpartners.com",
    overview: "The makers of Candy Crush created a whimsical workspace divided into interactive nature zones like 'Magic Forest', 'Treasure Island', and 'Sandy Dunes' to stimulate game design.",
    esgContext: "Energy Star rated appliances, LED mood lighting zones, locally manufactured Scandinavian birch components, and complete carpet recycling programs.",
    designHighlights: [
      "Custom indoor timber treehouses serving as private team collaboration spaces",
      "Caravan meeting pods equipped with high-performance game-testing consoles",
      "Soft acoustic hills providing ergonomic informal lounge seating for laptop work",
      "Trampoline recreation areas for physical decompression between coding sprints"
    ],
    materials: ["Scandinavian Birch plywood", "Acoustic green turf", "Molded fiberglass shells", "Custom wool felt cushions"]
  },
  {
    id: "shopify-ottawa-hq",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Ottawa",
    country: "Canada",
    typology: "contact",
    esgRating: "LEED Gold Certified",
    area: "16,000 m²",
    year: "2014",
    image: "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://linebox.ca",
    overview: "Spanning multiple floors in downtown Ottawa, each level is an interactive journey through creative commerce, featuring shipping container phone booths and modular whiteboard pods.",
    esgContext: "Certified LEED Gold. Advanced occupancy sensors optimize HVAC flow, while interior materials reuse historic Canadian timber and steel beams.",
    designHighlights: [
      "Repurposed steel shipping containers transformed into acoustic telephone booths",
      "Whiteboard walls wrapping every corridor for spontaneous algorithm sketching",
      "Cozy speakeasy lounges featuring Canadian whiskey barrels and warm fireplace fixtures",
      "Ergonomic sit-stand desk arrays with decentralized micro-kitchens"
    ],
    materials: ["Corten steel panels", "Canadian Maple wood", "Reclaimed red brick", "Acoustic cork wall tiles"]
  },
  {
    id: "macquarie-ropemaker",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "London",
    country: "United Kingdom",
    typology: "contact",
    esgRating: "BREEAM Excellent",
    area: "20,000 m²",
    year: "2011",
    image: "https://images.unsplash.com/photo-1497366412874-3415097a27e7?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://clivewilkinson.com",
    overview: "A groundbreaking transformation of traditional investment banking into an open, agile workplace connected by a dramatic red steel sculptural staircase through a central atrium.",
    esgContext: "BREEAM Excellent certified, slashing energy usage by 40% and eliminating 85% of paper filing storage through digitized activity-based operations.",
    designHighlights: [
      "Monumental continuous red steel staircase visually connecting all banking floors",
      "Themed 'neighborhood' work plazas offering privacy without physical walls",
      "High-performance acoustic ceiling pods preventing ambient noise bleed",
      "Central barista coffee hub promoting spontaneous cross-divisional meetings"
    ],
    materials: ["Vibrant red coated structural steel", "Solid oak meeting tables", "Acoustic micro-slat ceilings", "Polished terrazzo"]
  },
  {
    id: "patagonia-ventura-hq",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Ventura, CA",
    country: "United States",
    typology: "contact",
    esgRating: "B Corp Platinum & Solar Powered",
    area: "9,000 m²",
    year: "2019",
    image: "https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://patagonia.com",
    overview: "Nestled along the Ventura coast, Patagonia's headquarters embodies environmental activism with on-site childcare, surfboard lockers, reclaimed timber desks, and solar courtyards.",
    esgContext: "100% solar powered, zero waste to landfill operations, non-toxic finishes, and built entirely from salvaged regional materials and non-chemically treated organic fibers.",
    designHighlights: [
      "Desks built from salvaged regional fallen cedar and Monterey cypress trees",
      "On-site employee childcare center integrated into central sunny courtyards",
      "Open-air surf locker sheds encouraging mid-day ocean breaks when swells arrive",
      "Textile repair and testing laboratory visible directly from communal hallways"
    ],
    materials: ["Fallen Monterey Cypress", "Reclaimed barn wood", "Non-toxic natural oils", "Raw iron hardware"]
  },
  {
    id: "zalando-headquarters",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Berlin",
    country: "Germany",
    typology: "contact",
    esgRating: "DGNB Gold Certified",
    area: "42,000 m²",
    year: "2019",
    image: "https://images.unsplash.com/photo-1504384764586-bb4cdc1707b0?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://henn.com",
    overview: "Berlin's leading e-commerce tech hub transforms the traditional Berlin perimeter block with a diagonal glass atrium that encourages flow, visibility, and high-energy interaction.",
    esgContext: "Certified DGNB Gold. Outfitted with high-efficiency heat recovery, kinetic facade sunshades, and rainwater harvesting that waters all interior gardens.",
    designHighlights: [
      "Sweeping dynamic central catwalks and bleacher stairs fostering serendipity",
      "Sound-controlled micro-lounges offering privacy in an open-plan environment",
      "Rooftop basketball and athletic facilities overlooking Berlin's Spree river",
      "Living interior tree groves providing fresh oxygen and visual softness"
    ],
    materials: ["Architectural fair-faced concrete", "Light Douglas fir timber", "Acoustic ceiling baffles", "Low-iron structural glass"]
  },
  {
    id: "pwc-barangaroo",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Sydney",
    country: "Australia",
    typology: "contact",
    esgRating: "6 Star Green Star & WELL Platinum",
    area: "28,000 m²",
    year: "2017",
    image: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://futurespace.com.au",
    overview: "Overlooking Sydney Harbour, this professional services workplace redefines consulting by dedicating four full floors exclusively to immersive client co-creation and innovation labs.",
    esgContext: "6 Star Green Star certified. World-first zero-carbon precinct powered by harbour-water heat rejection and 100% renewable power purchase agreements.",
    designHighlights: [
      "Client innovation zones featuring multi-touch interactive digital war rooms",
      "Dramatic internal spiral stair made from sustainably sourced Australian Blackwood",
      "Bespoke barista bars offering world-class coffee and casual meeting corners",
      "Acoustically isolated negotiation suites with high speech confidentiality ratings"
    ],
    materials: ["Australian Blackwood", "Polished Sydney sandstone", "Acoustic wool fabric", "High-performance glass"]
  },
  {
    id: "riot-games-campus",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Los Angeles, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Silver Certified",
    area: "26,000 m²",
    year: "2015",
    image: "https://images.unsplash.com/photo-1497215641119-bbe6d71eeeae?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://riotgames.com",
    overview: "A former aerospace warehouse transformed into a player-first game development paradise, centered around a full-scale esports arena, Korean internet cafe (PC Bang), and coding suites.",
    esgContext: "Preserved 100% of historic bowstring wooden trusses, installing high-efficiency LED theatrical illumination and automated HVAC setback controls.",
    designHighlights: [
      "Historic bowstring wood trusses soaring over double-height creative pods",
      "Authentic on-site PC Bang cafe allowing developers to test games with live players",
      "Sound-isolated audio engineering suites for orchestral video game soundtrack recording",
      "Lush outdoor courtyards shaded by mature olive trees with outdoor WiFi"
    ],
    materials: ["Exposed bowstring wood trusses", "Industrial metal rebar", "Polished concrete slab", "Acoustic foam baffles"]
  },
  {
    id: "swiss-re-gherkin",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "London",
    country: "United Kingdom",
    typology: "contact",
    esgRating: "BREEAM Excellent",
    area: "47,950 m²",
    year: "2004",
    image: "https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://fosterandpartners.com",
    overview: "Inside London's legendary Norman Foster skyscraper, the interior floorplates spiral around six light-well atriums that provide natural cross-ventilation and 360-degree city views.",
    esgContext: "The aerodynamic exterior geometry forces air through interior spiral light shafts, cutting artificial heating and cooling demands by half compared to standard towers.",
    designHighlights: [
      "Panoramic top-floor private dining dome beneath the glass apex lens",
      "Spiraling light-well atriums pulling natural sunlight into core administrative desks",
      "Custom curved acoustic partitions conforming to the circular floor geometry",
      "Integrated solar tracking automated blinds along the double-glazed perimeter"
    ],
    materials: ["Double-curved low-E glass", "Anodized aluminum trim", "Acoustic micro-perforated wood", "Monolithic wool carpeting"]
  },
  {
    id: "google-spruce-goose",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Playa Vista, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Platinum Certified",
    area: "41,800 m²",
    year: "2018",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://zgf.com",
    overview: "Built inside the historic 1943 wooden aircraft hangar where Howard Hughes engineered the iconic Spruce Goose flying boat, this project inserts a contemporary 4-story timber workplace within the landmark shell.",
    esgContext: "LEED Platinum certified. Maintained 100% of the historic timber structural framework, avoiding over 15,000 metric tons of embodied carbon while adding high-efficiency envelope seals.",
    designHighlights: [
      "Spectacular 750-foot-long original timber glulam arches spanning over modern workstations",
      "Elevated boardwalk bridges and cascading stairs uniting floating work pods",
      "Custom daylight skylights washing the massive historic wooden ceiling with natural illumination",
      "Event theater and food hall designed as a celebration of aviation heritage"
    ],
    materials: ["Historic Douglas fir glulam", "Custom perforated acoustic metal", "Industrial sealed concrete", "Tempered structural glass"]
  },
  {
    id: "tiktok-london-kaleidoscope",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Farringdon, London",
    country: "United Kingdom",
    typology: "contact",
    esgRating: "BREEAM Outstanding",
    area: "8,200 m²",
    year: "2022",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://gensler.com",
    overview: "Perched directly atop Farringdon's Elizabeth Line station, this UK headquarters integrates creator production studios, live-streaming booths, and vibrant social cafes.",
    esgContext: "Certified BREEAM Outstanding. Zero fossil fuel building utilizing 100% renewable power, heat pump recovery, and extensive green roof terrace biodiversity.",
    designHighlights: [
      "Custom creator studios equipped with professional acoustic isolation and multi-color lighting",
      "Expansive rooftop terrace with outdoor meeting pods looking towards St. Paul's Cathedral",
      "Vibrant social town hall with stadium seating and high-resolution media walls",
      "Flexible agile benching with integrated acoustic felt cable management"
    ],
    materials: ["Recycled acoustic felt", "Bleached English oak", "Exposed concrete soffits", "Low-iron acoustic glazing"]
  },
  {
    id: "wise-london-hq",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "Shoreditch, London",
    country: "United Kingdom",
    typology: "contact",
    esgRating: "SKArating Gold Certified",
    area: "5,000 m²",
    year: "2021",
    image: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://thirdway.com",
    overview: "Located in East London's Tech City, Wise HQ emphasizes mission-driven transparency with open boardrooms, quiet library sanctuaries, and a wellness sauna zone.",
    esgContext: "Achieved SKA Gold rating for environmentally sustainable office fit-outs, diverting 98% of fit-out waste from landfills and using exclusively zero-VOC finishes.",
    designHighlights: [
      "Transparent all-glass executive boardrooms eliminating hierarchy",
      "Themed breakout zones named after global currencies with regional art tapestries",
      "Nordic wellness wing complete with an employee recovery sauna and meditation pods",
      "Central barista hub and event space hosting open-source developer hackathons"
    ],
    materials: ["Reclaimed industrial brick", "Blackened steel glass screens", "Nordic Spruce sauna timber", "Natural wool rugs"]
  },
  {
    id: "square-hq-sf",
    name: "Global Warming",
    firm: "www.linktr.ee/ESGrp",
    city: "San Francisco, CA",
    country: "United States",
    typology: "contact",
    esgRating: "LEED Gold Certified",
    area: "27,400 m²",
    year: "2015",
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=800&h=1000&q=80",
    badge: "LinkedIN",
    contactLink: "https://wa.me/60126185866",
    webLink: "https://bcj.com",
    overview: "Organized around a central 300-foot-long interior 'boulevard', this workplace mirrors urban civic circulation, encouraging impromptu encounters with continuous coffee bars and project tables.",
    esgContext: "Certified LEED Gold. Maximizes natural daylight penetration, features regional wood sourcing, low-flow plumbing, and extensive employee bike storage.",
    designHighlights: [
      "The Boulevard: A continuous urban promenade with high-top collaboration tables",
      "Amphitheater staircase connecting four levels of flexible open-plan desk neighborhoods",
      "Custom white oak conference cabanas with integrated acoustic sound baffles",
      "Central coffee roasting bar anchoring spontaneous meetings between engineers and designers"
    ],
    materials: ["White American Oak", "Precision brushed aluminum", "Acoustic fabric panels", "Polished concrete"]
  }
];
